### ISSUE TITLE
Is there a concise way to directly export generated STIX data as JSON file?

### ISSUE THREAD

**Issue by KnightChaser** [oasis-open/cti-stix-generator#55]
Well, this package is straightforward at generating a random STIX data and I'm satisfied at this level of convenience. However, when I try to load this as JSON data and save it to the data like the code below,

```py
import stix2generator
import json

stix2_generator = stix2generator.create_stix_generator()
stix = stix2_generator.generate()
stix_dump = json.dumps(stix, indent=4)
```

I get the errors below because some STIX SDO objects are not python default data types. (For example, the runtime exception log below says that the generated STIX data can't be converted to the JSON format since `Note` which is one of STIX SDO is not compatible.)
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\nis-ems-client\test\fake_stix2_generator.py", line 6, in <module>
    stix_dump = json.dumps(stix, indent=4)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.9\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.9\Lib\json\encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.9\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.9\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.9\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.9\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Note is not JSON serializable
```

So, my question is, is there a way to cope with this issue? I'm almost new to STIX, I just read the STIX documentation from the official page today and I am about to use STIX data with my project. Thanks in advance.

**Comment by KnightChaser** [comment]
It's possible to simply(maybe) parse the STIX2 generation result as a JSON dump with Python's JSON package(`json`) with STIX2's JSON serialization class object(`stix2.serialization.STIXJSONEncoder`).  :)

But note that the parsed STIX2 data is not the exactly same as the standard STIX2 format, so the schema validation via `stix2validator` will probably fail. We have to adjust the position of `id` properties of each STIX object. (Refer to the code below)

Here I'll attach a working makeshift example
```py
import stix2generator
import stix2validator
import stix2
import json
import uuid
from rich import print

# Generate the fake STIX2 data
stix2_generator = stix2generator.create_stix_generator()
stix = stix2_generator.generate()

# Convert the STIX data (Dictionary with STIX-proprietary objects) to pure JSON objects
def stix_to_json(stix_data):
    stix_objects = []
    for value in stix_data.values():
        stix_objects.append(json.loads(value.serialize()))
    return stix_objects

stix_objects = stix_to_json(stix)

# Create a STIX bundle with the generated objects
stix_bundle = {
    "type": "bundle",
    "id": f"bundle--{uuid.uuid4()}",
    "objects": stix_objects
}

# Convert the STIX bundle to JSON
stix_bundle_json = json.dumps(stix_bundle, cls=stix2.serialization.STIXJSONEncoder, indent=4).encode('utf-8').decode('utf-8')
print(stix_bundle_json)

# Validate the generated STIX bundle
result = stix2validator.validate_string(str(stix_bundle_json))
stix2validator.print_results(result)
```

**Comment by chisholm** [comment]
Not sure what you mean by repositioning the `id` property.  Abstractly speaking, mappings/objects don't have an intrinsic order to their entries (some implementations can allow you to control some kinds of ordering, e.g. a traversal order, but that is an implementation detail).  I don't think JSON-Schema allows you to express a required ordering on object entries (correct me if I am wrong).  So, it seems to me an object entry ordering difference cannot cause a JSON-Schema validation failure.

A simpler way to generate and validate is (but does not directly use the `json` package):

```python
import io
import sys
# ... and all the other imports

stix = stix2_generator.generate()
bundle = stix2.Bundle(list(stix.values()))

# A simple way to dump to stdout:
# (don't use pretty=True for large numbers of objects!)
bundle.fp_serialize(sys.stdout, pretty=True)

# A simple way to dump JSON to a memory text buffer
buf = io.StringIO()
bundle.fp_serialize(buf)

# Reposition for reading, and validate
buf.seek(0, io.SEEK_SET)
result = stix2validator.validate(buf)
stix2validator.print_results(result)
```

Even shorter, using a plain string instead of a string buffer:

```python
result = stix2validator.validate_string(bundle.serialize())
```

Or via shell:

```bash
# -b causes output to be wrapped in a bundle
generate_stix -b > ./bundle.json
stix2_validator ./bundle.json
```
